### ISSUE TITLE
Data privacy issue in Moodle 3.8

### ISSUE THREAD

**Issue by jelshoff** [elearningsoftware/moodle-mod_journal#60]
When running a GDPR data export request, the cron returns a fatal error:

Fatal error: Declaration of mod_journal\privacy\provider::get_metadata(core_privacy\local\metadata\collection $collection) must be compatible with core_privacy\local\metadata\provider::get_metadata(core_privacy\local\metadata\collection $collection): core_privacy\local\metadata\collection in .../mod/journal/classes/privacy/provider.php on line 43

This causes the general cron to hang while processing the data export task.

**Comment by amandadoughty** [comment]
Fix:

#72
public static function get_metadata(collection $collection) : collection {

#136
public static function get_contexts_for_userid(int $userid) : contextlist {

**Comment by jelshoff** [comment]
Shouldn't this be fixed by the developer and then deployed to moodle.org/plugins properly? That way all Moodle administrators will benefit.

**Comment by amandadoughty** [comment]
Of course. I just added the fix for the developer to hopefully get it in asap.

**Comment by jelshoff** [comment]
Understood... thanks for pointing to the fixes! I know this is an issue that was already mentioned on Moodle Community forums a few months ago, but strangely enough, it hasn't been fixed yet.

**Comment by argwallace** [comment]
I added these fixes into my version but I still get an error when I try to create a GDPR request. Am I missing something?

**Comment by danmarsden** [comment]
see pull request #48 for a fix - this was submitted almost 12 months ago now.

@elearningsoftware @adrian-sarmas  - is anyone maintaining this plugin on your end?

**Comment by adrian-sarmas** [comment]
I've merged the pull request. Thank you for your input
